org.gradle.jvmargs=-Xmx1400m -XX:MaxMetaspaceSize=448m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -XX:+UseSerialGC -XX:ActiveProcessorCount=2
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.workers.max=1
android.useAndroidX=true
android.nonTransitiveRClass=true
android.enableJetifier=false
kotlin.code.style=official
kotlin.incremental=true
kotlin.compiler.execution.strategy=in-process
android.suppressUnsupportedCompileSdk=36
android.experimental.enableArtProfiles=true
android.enableR8.fullMode=true
android.experimental.r8.dex-startup-optimization=true
